version: '3.1'

services:
  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 27018:27017
    env_file:
       - ".env"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080


  tgbot:
    container_name: bot
    build:
      context: .
    command: python main.py
    restart: always
    env_file:
      - ".env"



