services:

  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - "./env"
      POSTGRES_PASSWORD:

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  tg_bot:
    container_name: bot
    build:
      context: .
    command:
      - python3 main.py
    restart: always

    env_file:
      - "./env"



