version: '3.1'

services:
  db:
    # ВНИМАТЕЛЬНО! ВОТ ЭТО НАЗВАНИЕ СЕРВИСА - db - ДОЛЖНО БЫТЬ УКАЗАНО В БОТЕ КАК host В ПОДКЛЮЧЕНИИ К БАЗЕ ИЗ БОТА
    # ТО ЕСТЬ НЕ АЙПИШНИК И НЕ ЛОКАЛХОСТ, А db
    # DB_HOST: db
    container_name: database
    image: postgres
    restart: always
    ports:
      - 27018:27017
    env_file:
       - ".env"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080


  tgbot:
    container_name: bot
    build:
      context: .
    command: python main.py
    restart: always
    env_file:
      - ".env"






