version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2288

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  tgbot:
    container_name: bot
    build: .
    volumes:
      - .:/src
    command: python main.py
    restart: always
    network_mode: "host"
    env_file:
      - ".env"
    depends_on:
      - db



